logging:
  file: logs/condenser-it.log

spring:
  jmx:
    port: 49003
  data:
    elasticsearch:
      repositories:
        enabled: false

server:
  port: 48003

infrastructure:
  environment-name: it
  amqp-camel-component: rabbitmq
  amqp-server: localhost:5672
  amqp-ticks-exchange: turbine.it.market.ticks
  amqp-indicators-exchange: turbine.it.market.indicators
  amqp-strategies-exchange: turbine.it.market.strategies
  amqp-ticks-queue: turbine.it.queue.ticks
  amqp-indicators-queue: turbine.it.queue.indicators
  amqp-strategies-queue: turbine.it.queue.strategies
  elasticsearch-camel-component: stub
  elasticsearch-cluster: elasticsearch
  elasticsearch-host: localhost
  elasticsearch-native-port: 9300
  elasticsearch-rest-port: 9200
  elasticsearch-index-for-ticks: turbine-ticks
  elasticsearch-index-for-indicators: turbine-indicators
  elasticsearch-index-for-strategies: turbine-strategies
  elasticsearch-type-for-ticks: turbine-tick
  elasticsearch-type-for-indicators: turbine-indicator
  elasticsearch-type-for-strategies: turbine-strategy
  websocket-camel-component: stub
  websocket-ticks: /topic/ticks
  websocket-indicators: /topic/indicators
  websocket-strategies: /topic/strategies
  websocket-reply: /topic/reply
  
  
